title: "Jihun Yang"
description: "Personal Portfolio & Knowledge Archive"

url: "https://jihunyangkr.github.io"
baseurl: ""

author:
  name: "Jihun Yang"

lang: "ko"

markdown: kramdown
theme: null

permalink: /:categories/:title/

collections:
  profiles:
    output: true
    permalink: /profiles/:name/
